import asyncio
import os
import edge_tts

AUDIO_DIR = r"c:\books\08_acoustic_resonance_audio_forensics\video_assets\audio"
os.makedirs(AUDIO_DIR, exist_ok=True)

VOICE_NARRATOR = "en-US-ChristopherNeural"
VOICE_ALEXA = "en-US-JennyNeural"

SCENES = [
    {
        "id": "scene1_crisis",
        "voice": VOICE_NARRATOR,
        "text": (
            "Welcome to AcousticShield, engineered for the Amazon Developer Hackathon Alexa Plus track. "
            "In 2026, streaming platforms face an unprecedented crisis: millions of synthetic AI instrumental tracks "
            "from Suno and Udio are flooding algorithmic playlists, diluting royalties and siphoning income away from human artists."
        )
    },
    {
        "id": "scene2_flaw",
        "voice": VOICE_NARRATOR,
        "text": (
            "Conventional audio deepfake detectors were built for human speech, relying on vocal tract formants and pitch cycles. "
            "When applied to multi-instrumental polyphony, orchestral acoustics, and complex classical music, they collapse with catastrophic false alarm rates, "
            "falsely accusing legendary human recordings while missing AI-generated tracks."
        )
    },
    {
        "id": "scene3_resonance",
        "voice": VOICE_NARRATOR,
        "text": (
            "AcousticShield introduces the Neural Codec Resonance Principle for instrumental music. "
            "AI generators synthesize audio using discrete Residual Vector Quantization codebooks. "
            "This leaves unavoidable physical artifacts: ultrasonic brickwalls between 16 and 18.5 kilohertz, "
            "artificial stereo Haas phase collapse, and an anomalous multi-resolution STFT resonance surge upon neural inversion."
        )
    },
    {
        "id": "scene4_alexa",
        "voice": VOICE_ALEXA,
        "text": (
            "Warning. This instrumental track was generated by synthetic AI with 99.4 percent confidence. "
            "Discrete ultrasonic cutoff detected at 17.2 kilohertz. Stream royalties have been safeguarded for human musicians, "
            "and an Ed25519 forensic dossier has been archived to Amazon S3."
        )
    },
    {
        "id": "scene4_narrator",
        "voice": VOICE_NARRATOR,
        "text": (
            "Embedded directly into the Amazon Music mobile app and Echo Show devices, AcousticShield evaluates incoming audio streams in under 50 milliseconds. "
            "Listener playback remains instantaneous, while catalog integrity is preserved automatically."
        )
    },
    {
        "id": "scene5_benchmark",
        "voice": VOICE_NARRATOR,
        "text": (
            "In rigorous empirical validation against twenty full-length instrumental tracks—comparing classical masters like Mozart, Chopin, and Beethoven "
            "against Suno AI instrumentals—AcousticShield achieved 95 percent accuracy and a perfect 100 percent human specificity with zero false accusations. "
            "The full benchmark dataset is publicly accessible on Hugging Face."
        )
    },
    {
        "id": "scene6_architecture",
        "voice": VOICE_NARRATOR,
        "text": (
            "Powered by AWS Bedrock Agents with Claude 3.5 Sonnet, the Model Context Protocol specification, and ECS Fargate containers, "
            "AcousticShield delivers autonomous, tamper-evident copyright protection for the entire Amazon ecosystem. "
            "Protecting human artistry with physical acoustic science."
        )
    }
]

async def generate_all():
    print("Generating studio voiceovers with Edge-TTS for AI Music Sentry...")
    for s in SCENES:
        out_path = os.path.join(AUDIO_DIR, f"{s['id']}.mp3")
        comm = edge_tts.Communicate(s["text"], s["voice"])
        await comm.save(out_path)
        print(f"  [OK] Generated {s['id']}.mp3 ({s['voice']})")

if __name__ == "__main__":
    asyncio.run(generate_all())
