[theme]
primaryColor = "#ff9900"
backgroundColor = "#0b0f14"
secondaryBackgroundColor = "#151b23"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
